### ISSUE TITLE
Websockets on iOS Safari

### ISSUE THREAD

**Issue by hugomallet** [cameronhunter/local-ssl-proxy#100]
Hi,

On Safari iOS 12.4, i get the following error when i try to connect to a web socket server on my local network : 

> WebSocket network error: The operation couldn’t be completed. (OSStatus error -9807.)

It seems that the self signed certificate are not accepted for ws communications.

I tried to validate the certificate manually by opening the web socket server as a web page in a new tab. The web page is displayed correctly but the wss establishment still fail.

Any idea ?

**Comment by cameronhunter** [comment]
`v2.0.2` uses a certificate created by `mkcert` as @Toumash suggests. Give it a try and it might resolve the issue.
