### ISSUE TITLE
Arbitrary Code Execution in underscore via a transitive dependency on nomnom

### ISSUE THREAD

**Issue by akoumany** [cameronhunter/local-ssl-proxy#104]
Hi there @cameronhunter 

Huge thanks for putting this together. Dependabot found a vulnerability in `underscore@~1.6.0` via a transitive dependency on `nomnom@1.8.1`. 

I see that [nomnom](https://github.com/harthur/nomnom) is 10 years old and unmaintained, any plans to update packages? 

If not, do you have time to review and merge a fix if I put in the work?

**Comment by cameronhunter** [comment]
I've removed the dependency on `nomnom` in `v2.0.0`
