### ISSUE TITLE
Request failed to proxy: ECONNREFUSED Node.js 18

### ISSUE THREAD

**Issue by davidrhoderick** [cameronhunter/local-ssl-proxy#108]
I saw another issue here for the same bug but that was opened in 2017 for Node.js version 17 originally.  Today I upgraded to Node.js 18 and I see that I'm getting the same issue.  Basically, when I try to run `local-ssl-proxy --source 3000 --target 3001` I get the following response:
![image](https://user-images.githubusercontent.com/2300366/211017880-0c42fda4-202a-445e-9166-8f86b0981c65.png)
And in the console log:
```Request failed to proxy: ECONNREFUSED```
I've tried add `NODE_OPTIONS=--dns-result-order=ipv4first ` in front of the command but it still fails.

**Comment by davidrhoderick** [comment]
I've also tried to make a certificate for `localhost` and for the domain I was using `vrio.development` and that didn't work.

**Comment by TheMatrixan** [comment]
Go to your `.bashrc` or other shell config file and add:
```shell
export NODE_OPTIONS=--dns-result-order=ipv4first
```
Then, rerun your terminal and start ssl script, it should work now.

**Comment by cameronhunter** [comment]
I've tested `v2.0.2` on all LTS versions of node, and I can't reproduce it. Could you give the latest version a try and see if it resolves the issue?
