### ISSUE TITLE
Security vulnerability in nomnom dependency

### ISSUE THREAD

**Issue by chingc** [cameronhunter/local-ssl-proxy#110]
local-ssl-proxy is causing security vulnerability warnings coming from the nomnom dependency.

It looks like this has already been addressed over a month ago in https://github.com/cameronhunter/local-ssl-proxy/pull/106 (thanks @dooart) but the changes still haven’t been published to npm (https://www.npmjs.com/package/local-ssl-proxy).

If someone can publish the latest changes it would be much appreciated.

**Comment by cameronhunter** [comment]
Released as part of `v2.0.0`
