### ISSUE TITLE
Request failed to proxy: ECONNRESET

### ISSUE THREAD

**Issue by pochemuto** [cameronhunter/local-ssl-proxy#9]
I'm trying to proxy to GWT codeServer:
1. Start proxy with local-ssl-proxy --source 9899 --target 9876
2. Browser sends request 'https://127.0.0.1:9899/recompile/Mbo?locale=ru&user.agent=safari&_callback=__gwt_bookmarklet_globals.callbacks.c0'
3. codeServer handles it and starts processing
4. in console message `Request failed to proxy: ECONNRESET` appears
5. looks like codeServer receives request again. It starts processing

If I try send same request using curl, it prints after some seconds
`curl: (56) SSLRead() return error -9806`

MacOS, El Capitan

**Comment by andrewmclagan** [comment]
yeah also see this a lot

**Comment by cameronhunter** [comment]
I can't reproduce. If you can write a test-case then please do so, and someone can work to fix it.
