### ISSUE TITLE
Make a proxy with Custom DNS

### ISSUE THREAD

**Issue by Tin-Nguyen** [cameronhunter/local-ssl-proxy#97]
Hi team,

I cannot figure out a way to make a proxy with Custom DNS like
`https://dev.mysite.com:3000` => `http://dev.mysite.com:3000`

Do you think it's possible to do? Note: I added the DNS into my hosts file already

**Comment by Tin-Nguyen** [comment]
@cameronhunter @trisecta @greenkeeperio-bot ?

**Comment by cameronhunter** [comment]
Ad @Toumash mentions you can't proxy to the same port. You can use a custom hostname using `--hostname`, but you must also provide your own `--cert` and `--key`.
