### ISSUE TITLE
Request failed to proxy: ECONNREFUSED

### ISSUE THREAD

**Issue by francisrod01** [cameronhunter/local-ssl-proxy#98]
This package don't run.

```
$ local-ssl-proxy --source 9001 --target 9000
```

Started proxy: https://localhost:9001 → http://localhost:9000
Request failed to proxy: ECONNREFUSED

**Comment by leonardoResendeLima** [comment]
+1. Same problem here.

**Comment by doerme** [comment]
+1

**Comment by adxy** [comment]
For me downgrading to `Node v14.18.2` solved this issue

**Comment by fcisio** [comment]
Hi, has anyone figured out the source of this issue?
It was working for me yesterday but now fails today (so I doubt that changing the version of node is the solution).

Upon restarting my computer, it now works.

So my guess is that it's an issue with the proxy not being killed properly at some point.
I'll need to test this theory next time I face this issue, but this command should technically work.

`lsof -n -i4TCP:{YOUR_PORT}`

**Comment by azhararmar** [comment]
I am having the same issue, when I try accessing the URL I get the error `Request failed to proxy: ECONNREFUSED` I have Node verion 17.2.0

**Comment by mrlasers** [comment]
I am also having this issue running Node 17.8.0. Downgrading to 16.13.0 resolved it.

**Comment by dawidjaniga** [comment]
Hi, I'm having error "Request failed to proxy: ECONNREFUSED" on Node 17.3
It works fine on 16.13.1

**Comment by tayloraucoin** [comment]
This still happens to be on all the node versions listed so far.

**Comment by Legym** [comment]
Just wanted to make a quick update, but make sure you're running the commands for the source and target. I ran into where the source was running, but the target wasnt. I am using nextjs and just needed to run `npm run dev`

**Comment by sebmellen** [comment]
Just a note for myself and anyone else who may be having this error, in my case I needed to explicitly set the `PORT` that my target app was running at.

**Comment by coffenbacher** [comment]
`NODE_OPTIONS=--dns-result-order=ipv4first npx local-ssl-proxy -s 9000 -t 3000`

is working for me 🎉 Those of you mentioning Node 17 reminded me of that breaking change to the network stack there, I have no idea why it would be an issue in this package but I was able to repro over and over on my machine at least.

**Comment by bel7aG** [comment]
Make sure that your application server is running on the target port.

eg. `local-ssl-proxy --source 3001 **--target 3000**) & next dev **--port 3000**`

**Comment by cameronhunter** [comment]
I've released `v2.0.1`, which I've tested works on all LTS versions of node – I hope this resolves the issue.

**Comment by amplexus** [comment]
I had this issue when my nextjs app got into an endless loop due to incorrect use of useEffect. I killed the proxy, but when I restarted it I got ECONNREFUSED. Running `netstat -an` showed no process listening on that port, so this was somewhat confusing. However, closing the browser tab of the errant nextjs app allowed the proxy to startup again.
