### ISSUE TITLE
Lets encrypt certificate instead of the self signed one

### ISSUE THREAD

**Issue by ddehghan** [cameronhunter/local-ssl-proxy#99]
It would be very nice if you could get a certificate that does not trigger the browser warnings.

**Comment by friksa** [comment]
Would be nice to integrate with [mkcert](https://github.com/FiloSottile/mkcert)

**Comment by cameronhunter** [comment]
I don't currently have a use-case for this package so I'm not spending time on it. PRs are open if someone wants to tackle it though.
